[project]
name = "quantum-error-correction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "intel-extension-for-pytorch>=2.8.0",
    "jupyter>=1.1.1",
    "numpy>=2.2.6",
    "torch>=2.9.0",
]
